# Generated by Django 6.0.3 on 2026-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_codes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_type',
            field=models.CharField(choices=[('code', 'ส่งโค้ด / คีย์สินค้า'), ('account', 'เติมเข้าบัญชีเกม')], default='code', max_length=20),
        ),
    ]
