# Generated by Django 6.0.3 on 2026-04-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='ชื่อเกม')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='games/logos/', verbose_name='โลโก้เกม')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเกม')),
            ],
            options={
                'verbose_name': 'เกม',
                'verbose_name_plural': 'รายชื่อเกม',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('platform', 'Platform'), ('genre', 'Game Category'), ('product', 'Product Category')], default='product', max_length=20, verbose_name='ประเภทหมวดหมู่')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='store.category', verbose_name='Platform')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.game', verbose_name='เกม')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่ทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='Tab05CrossPlatform',
            fields=[
            ],
            options={
                'verbose_name_plural': '05. เกม Cross-Platform (มีหลายแพลตฟอร์ม)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Tab08Platform',
            fields=[
            ],
            options={
                'verbose_name_plural': '08. Platform',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Tab09Genre',
            fields=[
            ],
            options={
                'verbose_name_plural': '09. หมวดเกม',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Tab10ProductCat',
            fields=[
            ],
            options={
                'verbose_name_plural': '10. หมวดสินค้า',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Tab02GameAll',
            fields=[
            ],
            options={
                'verbose_name_plural': '02. เกมทั้งหมด',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.game',),
        ),
        migrations.CreateModel(
            name='Tab03GamePC',
            fields=[
            ],
            options={
                'verbose_name_plural': '03. เกม PC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.game',),
        ),
        migrations.CreateModel(
            name='Tab04GameMobile',
            fields=[
            ],
            options={
                'verbose_name_plural': '04. เกม Mobile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.game',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='จำนวนในสต็อก')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='ยอดขาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='พร้อมขาย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='หมวดหมู่สินค้า')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.game', verbose_name='เกม')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'คลังสินค้า',
            },
        ),
        migrations.CreateModel(
            name='Tab01ProductAll',
            fields=[
            ],
            options={
                'verbose_name_plural': '01. สินค้าทั้งหมด',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
    ]
