# Generated by Django 6.0.3 on 2026-04-17 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'genre'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_genres', to='store.category', verbose_name='หมวดเกม (Genre)'),
        ),
    ]
