# Generated by Django 6.0.3 on 2026-04-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_game_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tab05CrossPlatform',
        ),
        migrations.DeleteModel(
            name='Tab08Platform',
        ),
        migrations.DeleteModel(
            name='Tab09Genre',
        ),
        migrations.DeleteModel(
            name='Tab10ProductCat',
        ),
        migrations.CreateModel(
            name='Tab05Platform',
            fields=[
            ],
            options={
                'verbose_name_plural': '05. จัดการ Platform (PC/Mobile)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Tab06Genre',
            fields=[
            ],
            options={
                'verbose_name_plural': '06. จัดการหมวดเกม (Genre)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Tab07ProductCat',
            fields=[
            ],
            options={
                'verbose_name_plural': '07. จัดการหมวดสินค้า (Type)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.AlterModelOptions(
            name='tab02gameall',
            options={'verbose_name_plural': '02. รายชื่อเกมทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='tab03gamepc',
            options={'verbose_name_plural': '03. เกมเฉพาะ PC'},
        ),
        migrations.AlterModelOptions(
            name='tab04gamemobile',
            options={'verbose_name_plural': '04. เกมเฉพาะ Mobile'},
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'platform'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_platforms', to='store.category', verbose_name='แพลตฟอร์ม'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=0, verbose_name='รายละเอียดเกม'),
            preserve_default=False,
        ),
    ]
