# Generated by Django 6.0.3 on 2026-04-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_tab05crossplatform_delete_tab08platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='URL Slug'),
        ),
    ]
