# Generated by Django 6.0.3 on 2026-04-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab08OutOfStock',
            fields=[
            ],
            options={
                'verbose_name_plural': '08. สินค้าหมดสต็อก',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.AlterModelOptions(
            name='tab01productall',
            options={'verbose_name_plural': '01. สินค้าพร้อมขาย'},
        ),
        migrations.AlterModelOptions(
            name='tab05platform',
            options={'verbose_name_plural': '05. จัดการ Platform'},
        ),
        migrations.AlterModelOptions(
            name='tab06genre',
            options={'verbose_name_plural': '06. จัดการหมวดเกม'},
        ),
        migrations.AlterModelOptions(
            name='tab07productcat',
            options={'verbose_name_plural': '07. จัดการหมวดสินค้า'},
        ),
    ]
