# Generated by Django 6.0.3 on 2026-04-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tab08outofstock_alter_tab01productall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account_input_help',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='คำแนะนำช่องหลัก'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_input_label',
            field=models.CharField(blank=True, default='UID / Player ID', max_length=120, verbose_name='ชื่อช่องกรอกข้อมูลหลัก'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_input_placeholder',
            field=models.CharField(blank=True, default='กรอก UID หรือรหัสผู้เล่น', max_length=180, verbose_name='ข้อความตัวอย่างช่องหลัก'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_input_secondary_help',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='คำแนะนำช่องรอง'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_input_secondary_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='ชื่อช่องกรอกข้อมูลรอง'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_input_secondary_placeholder',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='ข้อความตัวอย่างช่องรอง'),
        ),
        migrations.AddField(
            model_name='product',
            name='fulfillment_type',
            field=models.CharField(choices=[('code', 'ส่งโค้ด / คีย์สินค้า'), ('account', 'เติมเข้าบัญชีเกม')], default='code', max_length=20, verbose_name='รูปแบบการส่งมอบสินค้า'),
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='โค้ด / คีย์สินค้า')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='หมายเหตุ')),
                ('is_used', models.BooleanField(default=False, verbose_name='ถูกใช้งานแล้ว')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ถูกใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มโค้ด')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_items', to='store.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'โค้ดสินค้า',
                'verbose_name_plural': 'คลังโค้ดสินค้า',
            },
        ),
    ]
