# Generated by Django 6.0.3 on 2026-04-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_account_input_help_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account_input_help',
        ),
        migrations.RemoveField(
            model_name='product',
            name='account_input_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='account_input_placeholder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='account_input_secondary_help',
        ),
        migrations.RemoveField(
            model_name='product',
            name='account_input_secondary_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='account_input_secondary_placeholder',
        ),
    ]
