# Generated by Django 6.0.3 on 2026-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_account_input_help_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='account_input_help',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Extra setting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_input_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Extra setting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_input_placeholder',
            field=models.CharField(blank=True, max_length=180, verbose_name='Extra setting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_input_secondary_help',
            field=models.CharField(blank=True, max_length=255, verbose_name='Extra setting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_input_secondary_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Extra setting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_input_secondary_placeholder',
            field=models.CharField(blank=True, max_length=180, verbose_name='Extra setting'),
        ),
    ]
