# Generated by Django 6.0.3 on 2026-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
