# Generated by Django 6.0.3 on 2026-04-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'ผู้ดูแลระบบ', 'verbose_name_plural': '1. รายชื่อแอดมิน'},
        ),
        migrations.AlterModelOptions(
            name='playeruser',
            options={'verbose_name': 'ผู้เล่น', 'verbose_name_plural': '2. รายชื่อผู้เล่น'},
        ),
    ]
