# Generated by Django 6.0.3 on 2026-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_adminuser_options_alter_playeruser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='ยืนยันอีเมลแล้ว'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่ล็อกอินผิด'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ล็อกอินได้อีกครั้งเมื่อ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_change_count',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่เปลี่ยนรหัสผ่าน'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='ยืนยันเบอร์แล้ว'),
        ),
    ]
