# Generated by Django 6.0.3 on 2026-04-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ยอดเงินคงเหลือ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'กระเป๋าเงิน',
                'verbose_name_plural': 'กระเป๋าเงินทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'เติมเงิน'), ('WITHDRAW', 'ถอนเงิน/ชำระเงิน')], max_length=10, verbose_name='ประเภทรายการ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาทำรายการ')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'ประวัติธุรกรรม',
                'verbose_name_plural': 'ประวัติธุรกรรมทั้งหมด',
            },
        ),
    ]
