# Generated by Django 6.0.3 on 2026-04-18 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'ประวัติธุรกรรม', 'verbose_name_plural': 'ประวัติธุรกรรมทั้งหมด'},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'เติมเงิน'), ('WITHDRAW', 'ถอนเงิน/ชำระเงิน')], max_length=20, verbose_name='ประเภทรายการ'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet', verbose_name='กระเป๋าเงิน'),
        ),
    ]
